---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.128.0.60
    conditions:
      ready: false
      serving: false
      terminating: false
    nodeName: ip-10-0-1-102.ec2.internal
    targetRef:
      kind: Pod
      name: my-backstage-1-no-local-db-developer-hub-56fbb8cf48-gzwxj
      namespace: my-ns-3
      uid: fbe184ee-3313-4dcb-8c3c-c74b446c8b4c
    zone: us-east-1d
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T11:08:19Z"
    creationTimestamp: "2025-10-23T11:08:14Z"
    generateName: my-backstage-1-no-local-db-developer-hub-
    generation: 2
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: upstream-2.6.1
      kubernetes.io/service-name: my-backstage-1-no-local-db-developer-hub
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"7e2c372e-5680-45c0-af5c-727b48f13d8f"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-10-23T11:09:52Z"
    name: my-backstage-1-no-local-db-developer-hub-fztwg
    namespace: my-ns-3
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: my-backstage-1-no-local-db-developer-hub
      uid: 7e2c372e-5680-45c0-af5c-727b48f13d8f
    resourceVersion: "39833"
    uid: 741c6580-423b-4074-83df-354f5302f74e
  ports:
  - name: http-backend
    port: 7007
    protocol: TCP
  - name: http-metrics
    port: 9464
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "42051"
