apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2025-10-23T09:44:56Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: my-rhdh
    app.kubernetes.io/name: backstage
  name: backstage-psql-my-rhdh
  namespace: my-ns
  ownerReferences:
  - apiVersion: rhdh.redhat.com/v1alpha4
    blockOwnerDeletion: true
    controller: true
    kind: Backstage
    name: my-rhdh
    uid: 66af0070-357e-4be2-a571-6706ec838dcb
  resourceVersion: "1554"
  uid: dbdfad67-4e03-4ab3-97e1-1d67e7e6f4bd
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      rhdh.redhat.com/app: backstage-psql-my-rhdh
  serviceName: backstage-psql-my-rhdh
  template:
    metadata:
      creationTimestamp: null
      labels:
        rhdh.redhat.com/app: backstage-psql-my-rhdh
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_VOLUME_DIR
          value: /var/lib/pgsql/data
        - name: PGDATA
          value: /var/lib/pgsql/data/userdata
        envFrom:
        - secretRef:
            name: backstage-psql-secret-my-rhdh
        image: quay.io/fedora/postgresql-15:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: postgresql
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - |
              exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 20Mi
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 0
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /var/lib/pgsql/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: backstage-psql-my-rhdh-784b8f4f75
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: backstage-psql-my-rhdh-784b8f4f75
  updatedReplicas: 1
