#!/usr/bin/env bash

# Helm Data Collection Script
# Collects Helm-specific information for RHDH deployments

set -euo pipefail

# Get script directory for calling other scripts
DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
export_log_collection_args

log_info "Starting Ingress data collection..."

safe_exec "oc get ingresses.networking.k8s.io -A" "$BASE_COLLECTION_PATH/all-ingresses.txt" "All Ingresses"

# TODO Collect more details if needed
