#!/usr/bin/env bash

# Helm Data Collection Script
# Collects Helm-specific information for RHDH deployments

set -euo pipefail

# Get script directory for calling other scripts
DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
export_log_collection_args

log_info "Starting OCP Route data collection..."

safe_exec "oc get routes.route.openshift.io -A" "$BASE_COLLECTION_PATH/all-routes.txt" "All OCP routes"

# TODO Collect more details if needed