#!/usr/bin/env bash

set -euo pipefail

# Just testing PR workflow

function version() {
  if [[ ! -z "${RHDH_MUST_GATHER_VERSION:-}" ]] ; then
    echo "${RHDH_MUST_GATHER_VERSION}"
  else
    echo "0.0.0-$(git describe --no-match --always --abbrev=9 --dirty --broken 2>/dev/null || echo unknown)"
  fi
}
