apiVersion: v1
data:
  app-config.yaml: |
    app:
      baseUrl: https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com
    auth:
      providers: {}
    backend:
      auth:
        externalAccess:
        - options:
            secret: ${BACKEND_SECRET}
            subject: legacy-default-config
          type: legacy
      baseUrl: https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com
      cors:
        origin: https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com
      database:
        connection:
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          user: postgres
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1-no-local-db
    meta.helm.sh/release-namespace: my-ns-3
  creationTimestamp: "2025-10-23T09:47:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-backstage-1-no-local-db-developer-hub-app-config
  namespace: my-ns-3
  resourceVersion: "1780"
  uid: f4915acf-c593-450e-aad8-4c2d722bbfbc
