---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"metrics","app.kubernetes.io/created-by":"backstage-operator","app.kubernetes.io/instance":"controller-manager-metrics-service","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"service","app.kubernetes.io/part-of":"backstage-operator","control-plane":"controller-manager"},"name":"rhdh-controller-manager-metrics-service","namespace":"rhdh-operator"},"spec":{"ports":[{"name":"metrics","port":8443,"protocol":"TCP","targetPort":"metrics"}],"selector":{"control-plane":"controller-manager"}}}
    creationTimestamp: "2025-10-23T09:43:13Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/created-by: backstage-operator
      app.kubernetes.io/instance: controller-manager-metrics-service
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: service
      app.kubernetes.io/part-of: backstage-operator
      control-plane: controller-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/created-by: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:control-plane: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-10-23T09:43:13Z"
    name: rhdh-controller-manager-metrics-service
    namespace: rhdh-operator
    resourceVersion: "1219"
    uid: 0b47a059-236b-4b88-95a5-7d57df8643ea
  spec:
    clusterIP: 10.43.82.63
    clusterIPs:
    - 10.43.82.63
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
    selector:
      control-plane: controller-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "4661"
