apiVersion: v1
data:
  .npmrc: [REDACTED]
kind: Secret
metadata:
  annotations:
    rhdh.redhat.com/containers: install-dynamic-plugins
    rhdh.redhat.com/mount-path: /opt/app-root/src/.npmrc.dynamic-plugins
  creationTimestamp: "2025-10-23T11:12:30Z"
  labels:
    app.kubernetes.io/instance: my-developer-hub-op
    app.kubernetes.io/name: backstage
  name: backstage-files-my-developer-hub-op
  namespace: my-ns
  ownerReferences:
  - apiVersion: rhdh.redhat.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Backstage
    name: my-developer-hub-op
    uid: 61803723-6184-4c65-8836-9c7513554702
  resourceVersion: "40490"
  uid: d2eb43ec-dd51-4f71-bc3e-3fb5a468acf0
type: Opaque
