apiVersion: v1
data:
  .dockercfg: [REDACTED]
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: default
  creationTimestamp: "2025-10-23T07:52:50Z"
  name: default-dockercfg-k4hmt
  namespace: my-ns
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: default
    uid: 12834e58-065e-49b9-bf43-619b8fc5d51f
  resourceVersion: "36989"
  uid: 5d9a90f4-b859-4860-b049-cf3a464cb79d
type: kubernetes.io/dockercfg
