apiVersion: v1
data:
  password: [REDACTED]
  postgres-password: [REDACTED]
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: redhat-developer-hub-helm
    meta.helm.sh/release-namespace: my-ns
  creationTimestamp: "2025-10-23T11:11:18Z"
  labels:
    app.kubernetes.io/instance: redhat-developer-hub-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.10.0
  name: redhat-developer-hub-helm-postgresql
  namespace: my-ns
  resourceVersion: "40208"
  uid: a3fdff90-08cc-45cf-bbcf-2dd727f66b12
type: Opaque
