apiVersion: v1
data:
  host: [REDACTED]
  password: [REDACTED]
  port: [REDACTED]
  provider: [REDACTED]
  type: [REDACTED]
  uri: [REDACTED]
  username: [REDACTED]
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: redhat-developer-hub-helm
    meta.helm.sh/release-namespace: my-ns
  creationTimestamp: "2025-09-11T20:53:05Z"
  labels:
    app.kubernetes.io/instance: redhat-developer-hub-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.10.0
  name: redhat-developer-hub-helm-postgresql-svcbind-custom-user
  namespace: my-ns
  resourceVersion: "78766"
  uid: 35c1fe35-e9e1-48a3-8658-b1028e22647a
type: servicebinding.io/postgresql
