apiVersion: v1
data:
  release: [REDACTED]
kind: Secret
metadata:
  creationTimestamp: "2025-10-23T11:11:18Z"
  labels:
    modifiedAt: "1761217878"
    name: redhat-developer-hub-helm
    owner: helm
    status: deployed
    version: "1"
  name: sh.helm.release.v1.redhat-developer-hub-helm.v1
  namespace: my-ns
  resourceVersion: "40253"
  uid: 643e41da-ea71-4a64-b41e-6d08817811d5
type: helm.sh/release.v1
