---
apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: builder
    creationTimestamp: "2025-10-23T11:08:48Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"51efe8a4-7e67-445b-bd8a-a4f1238732e0"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    name: builder-dockercfg-5dq2d
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: builder
      uid: 51efe8a4-7e67-445b-bd8a-a4f1238732e0
    resourceVersion: "39098"
    uid: 3bb41dc9-3aa1-4e22-bf11-2a923056f780
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: default
    creationTimestamp: "2025-10-23T11:08:48Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"a8f75fd0-8383-451d-a888-4e159cef8681"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    name: default-dockercfg-fbwmw
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: default
      uid: a8f75fd0-8383-451d-a888-4e159cef8681
    resourceVersion: "39097"
    uid: 5bbd367b-f0a6-48db-95c5-36dd82791e21
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: deployer
    creationTimestamp: "2025-10-23T11:08:48Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"0015812c-afd4-4ed9-922f-8b069d44de9a"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:08:48Z"
    name: deployer-dockercfg-bvnxp
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: deployer
      uid: 0015812c-afd4-4ed9-922f-8b069d44de9a
    resourceVersion: "39099"
    uid: 669c4481-bbf0-4ae1-a3d4-56f2e3ad3582
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: rhdh-controller-manager
    creationTimestamp: "2025-10-23T11:09:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:09:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"98b2ebce-ab9a-4db9-9550-162213fe477e"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:09:11Z"
    name: rhdh-controller-manager-dockercfg-txz4s
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: rhdh-controller-manager
      uid: 98b2ebce-ab9a-4db9-9550-162213fe477e
    resourceVersion: "39285"
    uid: 791e365c-99d3-4ed8-bcb4-22ee8fb7566f
  type: kubernetes.io/dockercfg
kind: SecretList
metadata:
  resourceVersion: "42059"
