---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-23T11:09:11Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/created-by: backstage-operator
      app.kubernetes.io/instance: controller-manager-metrics-service
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: service
      app.kubernetes.io/part-of: backstage-operator
      control-plane: controller-manager
      olm.managed: "true"
      operators.coreos.com/rhdh.rhdh-operator: ""
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/created-by: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:control-plane: {}
            f:olm.managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"09dc6fb2-852d-459e-8003-3456ca9c4bc6"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: catalog
      operation: Update
      time: "2025-10-23T11:09:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:operators.coreos.com/rhdh.rhdh-operator: {}
      manager: olm
      operation: Update
      time: "2025-10-23T11:09:11Z"
    name: rhdh-controller-manager-metrics-service
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: rhdh-operator.v1.7.0
      uid: 09dc6fb2-852d-459e-8003-3456ca9c4bc6
    resourceVersion: "39270"
    uid: 56d169f0-c08e-4a4f-9f28-9301805b79f4
  spec:
    clusterIP: 172.30.38.95
    clusterIPs:
    - 172.30.38.95
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
    selector:
      control-plane: controller-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "42054"
