apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      rhdh.redhat.com/ext-config-hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    creationTimestamp: "2025-09-11T21:23:38Z"
    generateName: backstage-bs1-795679f5b9-
    labels:
      pod-template-hash: 795679f5b9
      rhdh.redhat.com/app: backstage-bs1
    name: backstage-bs1-795679f5b9-gmcnl
    namespace: my-ns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: backstage-bs1-795679f5b9
      uid: db62184c-7a13-44d3-a64c-28477a3715d0
    resourceVersion: "29261"
    uid: a7f33f4a-576d-4cb9-9221-c0e993719fb6
  spec:
    automountServiceAccountToken: false
    containers:
    - args:
      - --config
      - dynamic-plugins-root/app-config.dynamic-plugins.yaml
      - --config
      - /opt/app-root/src/default.app-config.yaml
      env:
      - name: APP_CONFIG_backend_listen_port
        value: "7007"
      envFrom:
      - secretRef:
          name: backstage-psql-secret-bs1
      image: quay.io/rhdh/rhdh-hub-rhel9:next
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /.backstage/health/v1/liveness
          port: backend
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 4
      name: backstage-backend
      ports:
      - containerPort: 7007
        name: backend
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /.backstage/health/v1/readiness
          port: backend
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 2
        timeoutSeconds: 4
      resources:
        limits:
          cpu: "1"
          ephemeral-storage: 5Gi
          memory: 2560Mi
        requests:
          cpu: 250m
          ephemeral-storage: 5Gi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      startupProbe:
        failureThreshold: 3
        httpGet:
          path: /.backstage/health/v1/liveness
          port: backend
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 4
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/app-root/src/dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /tmp
        name: temp
      - mountPath: /opt/app-root/src/default.app-config.yaml
        name: backstage-appconfig-bs1
        readOnly: true
        subPath: default.app-config.yaml
      workingDir: /opt/app-root/src
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
    - command:
      - ./install-dynamic-plugins.sh
      - /dynamic-plugins-root
      env:
      - name: NPM_CONFIG_USERCONFIG
        value: /opt/app-root/src/.npmrc.dynamic-plugins/.npmrc
      - name: MAX_ENTRY_SIZE
        value: "30000000"
      image: quay.io/rhdh/rhdh-hub-rhel9:next
      imagePullPolicy: IfNotPresent
      name: install-dynamic-plugins
      resources:
        limits:
          cpu: "1"
          ephemeral-storage: 5Gi
          memory: 2560Mi
        requests:
          cpu: 250m
          ephemeral-storage: 5Gi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /opt/app-root/src/.config/containers
        name: dynamic-plugins-registry-auth
        readOnly: true
      - mountPath: /opt/app-root/src/.npm/_cacache
        name: npmcacache
      - mountPath: /tmp
        name: temp
      - mountPath: /opt/app-root/src/dynamic-plugins.yaml
        name: backstage-dynamic-plugins-bs1
        readOnly: true
        subPath: dynamic-plugins.yaml
      - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
        name: backstage-files-bs1
      workingDir: /opt/app-root/src
    nodeName: k3d-local-1-agent-2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1001
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - ephemeral:
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            volumeMode: Filesystem
      name: dynamic-plugins-root
    - name: dynamic-plugins-registry-auth
      secret:
        defaultMode: 416
        optional: true
        secretName: dynamic-plugins-registry-auth
    - emptyDir: {}
      name: npmcacache
    - emptyDir: {}
      name: temp
    - configMap:
        defaultMode: 420
        name: backstage-appconfig-bs1
        optional: false
      name: backstage-appconfig-bs1
    - configMap:
        defaultMode: 420
        name: backstage-dynamic-plugins-bs1
        optional: false
      name: backstage-dynamic-plugins-bs1
    - name: backstage-files-bs1
      secret:
        defaultMode: 420
        optional: false
        secretName: backstage-files-bs1
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T21:26:13Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T21:27:26Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T21:28:16Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T21:28:16Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T21:23:45Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://fd9207930bfff621c2d9c56083526bad523ef3afe7523e7ec8d95ef200143f4e
      image: quay.io/rhdh/rhdh-hub-rhel9:next
      imageID: quay.io/rhdh/rhdh-hub-rhel9@sha256:43855fde5033d17dbe4130d9a6ae73901d6cdb5860cd81852e7768b6d0dd52ff
      lastState: {}
      name: backstage-backend
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-09-11T21:27:26Z"
      volumeMounts:
      - mountPath: /opt/app-root/src/dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /tmp
        name: temp
      - mountPath: /opt/app-root/src/default.app-config.yaml
        name: backstage-appconfig-bs1
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.3
    hostIPs:
    - ip: 172.18.0.3
    initContainerStatuses:
    - containerID: containerd://20737414bb2031fcf5f8359f235447871899a38305feccfe5f12f47bb5fc7253
      image: quay.io/rhdh/rhdh-hub-rhel9:next
      imageID: quay.io/rhdh/rhdh-hub-rhel9@sha256:43855fde5033d17dbe4130d9a6ae73901d6cdb5860cd81852e7768b6d0dd52ff
      lastState: {}
      name: install-dynamic-plugins
      ready: true
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: containerd://20737414bb2031fcf5f8359f235447871899a38305feccfe5f12f47bb5fc7253
          exitCode: 0
          finishedAt: "2025-09-11T21:27:24Z"
          reason: Completed
          startedAt: "2025-09-11T21:26:13Z"
      volumeMounts:
      - mountPath: /dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /opt/app-root/src/.config/containers
        name: dynamic-plugins-registry-auth
        readOnly: true
        recursiveReadOnly: Disabled
      - mountPath: /opt/app-root/src/.npm/_cacache
        name: npmcacache
      - mountPath: /tmp
        name: temp
      - mountPath: /opt/app-root/src/dynamic-plugins.yaml
        name: backstage-dynamic-plugins-bs1
        readOnly: true
        recursiveReadOnly: Disabled
      - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
        name: backstage-files-bs1
    phase: Running
    podIP: 10.42.2.7
    podIPs:
    - ip: 10.42.2.7
    qosClass: Burstable
    startTime: "2025-09-11T21:23:45Z"
kind: List
metadata:
  resourceVersion: ""
