COMPUTED VALUES:
serverlessLogicOperator:
  enabled: true
  subscription:
    namespace: openshift-serverless-logic
    spec:
      channel: alpha
      installPlanApproval: Manual
      name: logic-operator-rhel8
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: logic-operator-rhel8.v1.36.0
serverlessOperator:
  enabled: true
  subscription:
    namespace: openshift-serverless
    spec:
      channel: stable
      installPlanApproval: Manual
      name: serverless-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
tests:
  enabled: true
  image: bitnami/kubectl:latest
