---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/knatives.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/knatives.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
  namespace: rhdh-orchestrator-infra
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded, hook-failed
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-os
  namespace: openshift-serverless
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded, hook-failed
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions"]
    verbs: ["list", "get"]
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-osl
  namespace: openshift-serverless-logic
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded, hook-failed
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions"]
    verbs: ["list", "get"]
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-role-binding-os
  namespace: openshift-serverless
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded, hook-failed
subjects:
  - kind: ServiceAccount
    name: test-service-account
    namespace: rhdh-orchestrator-infra
roleRef:
  kind: Role
  name: test-role-os
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-role-binding-osl
  namespace: openshift-serverless-logic
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded, hook-failed
subjects:
  - kind: ServiceAccount
    name: test-service-account
    namespace: rhdh-orchestrator-infra
roleRef:
  kind: Role
  name: test-role-osl
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-developer-hub-orchestrator-infra/templates/tests/infra-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testing-pod
  namespace: rhdh-orchestrator-infra
  labels:
    app.kubernetes.io/component: test
  annotations:
    helm.sh/hook: test
spec:
  serviceAccountName: test-service-account
  containers:
    - name: oc-client
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: false
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 10m
          memory: 20Mi
      image: bitnami/kubectl:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
      
          echo "Starting Test"
            kubectl get subscription serverless-operator -n openshift-serverless || exit 1
          kubectl get subscription  -n openshift-serverless-logic || exit 1
      
          echo "Test passed!"
  restartPolicy: Never
