---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless-logic/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless-logic
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/knatives.yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  Registry:
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/knatives.yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  controller-custom-certs:
    name: ""
    type: ""
  registry: {}
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless-logic/operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless-logic
  namespace: openshift-serverless-logic
spec: {}
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless-operator-group
  namespace: openshift-serverless
spec: {}
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless-logic/subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: logic-operator-rhel8
  namespace: openshift-serverless-logic
spec:
  channel: alpha
  installPlanApproval: Manual
  name: logic-operator-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: logic-operator-rhel8.v1.36.0
---
# Source: redhat-developer-hub-orchestrator-infra/templates/serverless/subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
spec:
  channel: stable
  installPlanApproval: Manual
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

