---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-10-23T09:45:20Z"
  labels:
    kubernetes.io/metadata.name: my-ns-2
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: kubectl-create
    operation: Update
    time: "2025-10-23T09:45:20Z"
  name: my-ns-2
  resourceVersion: "1541"
  uid: c21af982-e2ca-4fed-a4a0-b64e0fdb77b7
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
