apiVersion: v1
data:
  .npmrc: [REDACTED]
kind: Secret
metadata:
  annotations:
    rhdh.redhat.com/containers: install-dynamic-plugins
    rhdh.redhat.com/mount-path: /opt/app-root/src/.npmrc.dynamic-plugins
  creationTimestamp: "2025-10-23T09:44:56Z"
  labels:
    app.kubernetes.io/instance: my-rhdh
    app.kubernetes.io/name: backstage
  name: backstage-files-my-rhdh
  namespace: my-ns
  ownerReferences:
  - apiVersion: rhdh.redhat.com/v1alpha4
    blockOwnerDeletion: true
    controller: true
    kind: Backstage
    name: my-rhdh
    uid: 66af0070-357e-4be2-a571-6706ec838dcb
  resourceVersion: "1415"
  uid: ff215f7d-d7a9-47d2-a45f-f51a60e67553
type: Opaque
