apiVersion: v1
data:
  POSTGRES_HOST: [REDACTED]
  POSTGRES_PASSWORD: [REDACTED]
  POSTGRES_PORT: [REDACTED]
  POSTGRES_USER: [REDACTED]
  POSTGRESQL_ADMIN_PASSWORD: [REDACTED]
kind: Secret
metadata:
  creationTimestamp: "2025-10-23T09:44:56Z"
  labels:
    app.kubernetes.io/instance: my-rhdh
    app.kubernetes.io/name: backstage
  name: backstage-psql-secret-my-rhdh
  namespace: my-ns
  ownerReferences:
  - apiVersion: rhdh.redhat.com/v1alpha4
    blockOwnerDeletion: true
    controller: true
    kind: Backstage
    name: my-rhdh
    uid: 66af0070-357e-4be2-a571-6706ec838dcb
  resourceVersion: "1410"
  uid: 747de2cc-6532-4ddc-83f5-5d4eaa221df2
type: Opaque
