apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  creationTimestamp: "2025-10-23T11:12:30Z"
  generation: 1
  labels:
    app.kubernetes.io/name: backstage
  name: my-developer-hub-op
  namespace: my-ns
  resourceVersion: "41433"
  uid: 61803723-6184-4c65-8836-9c7513554702
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
status:
  conditions:
  - lastTransitionTime: "2025-10-23T11:17:56Z"
    message: ""
    reason: Deployed
    status: "True"
    type: Deployed
