apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-10-23T11:09:13Z"
    generation: 1
    labels:
      app: rhdh-operator
      control-plane: controller-manager
      olm.deployment-spec-hash: afn8SmeSwoFpx8jU8uCE009VMMxp1HDhMUjPEt
      olm.managed: "true"
      olm.owner: rhdh-operator.v1.7.0
      olm.owner.kind: ClusterServiceVersion
      olm.owner.namespace: rhdh-operator
      operators.coreos.com/rhdh.rhdh-operator: ""
    name: rhdh-operator
    namespace: rhdh-operator
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: rhdh-operator.v1.7.0
      uid: 09dc6fb2-852d-459e-8003-3456ca9c4bc6
    resourceVersion: "39617"
    uid: e5cd90bf-5fb2-406f-a337-3306f1a0a0b9
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        app: rhdh-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          alm-examples: |-
            [
              {
                "apiVersion": "rhdh.redhat.com/v1alpha1",
                "kind": "Backstage",
                "metadata": {
                  "labels": {
                    "app.kubernetes.io/name": "backstage"
                  },
                  "name": "developer-hub"
                }
              },
              {
                "apiVersion": "rhdh.redhat.com/v1alpha2",
                "kind": "Backstage",
                "metadata": {
                  "labels": {
                    "app.kubernetes.io/name": "backstage"
                  },
                  "name": "developer-hub"
                }
              },
              {
                "apiVersion": "rhdh.redhat.com/v1alpha3",
                "kind": "Backstage",
                "metadata": {
                  "labels": {
                    "app.kubernetes.io/name": "backstage"
                  },
                  "name": "developer-hub"
                }
              }
            ]
          capabilities: Seamless Upgrades
          categories: Developer Tools
          certified: "true"
          containerImage: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:df3cbd7b2d58a346bdf0e42148792e76075293a055e7a523505131ee7274f956
          createdAt: "2025-07-02T07:33:16Z"
          description: Red Hat Developer Hub is a Red Hat supported version of Backstage.
            It comes with pre-built plug-ins and configuration settings, supports
            use of an external database, and can help streamline the process of setting
            up a self-managed internal developer portal for adopters who are just
            starting out.
          features.operators.openshift.io/cnf: "false"
          features.operators.openshift.io/cni: "false"
          features.operators.openshift.io/csi: "false"
          features.operators.openshift.io/disconnected: "true"
          features.operators.openshift.io/fips-compliant: "false"
          features.operators.openshift.io/proxy-aware: "false"
          features.operators.openshift.io/tls-profiles: "false"
          features.operators.openshift.io/token-auth-aws: "false"
          features.operators.openshift.io/token-auth-azure: "false"
          features.operators.openshift.io/token-auth-gcp: "false"
          kubectl.kubernetes.io/default-container: manager
          olm.operatorGroup: rhdh-operator-wtgrm
          olm.operatorNamespace: rhdh-operator
          olm.targetNamespaces: ""
          operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha1"}},{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha2"}},{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha3"}},{"type":"olm.package","value":{"packageName":"rhdh","version":"1.7.0"}}]}'
          operatorframework.io/suggested-namespace: rhdh-operator
          operators.openshift.io/valid-subscription: '["Red Hat Developer Hub"]'
          operators.operatorframework.io/builder: operator-sdk-v1.37.0
          operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
          repository: https://gitlab.cee.redhat.com/rhidp/rhdh/
          skipRange: '>=1.0.0 <1.7.0'
          support: Red Hat
        creationTimestamp: null
        labels:
          app: rhdh-operator
          app.kubernetes.io/component: rhdh-operator
          control-plane: controller-manager
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
        automountServiceAccountToken: true
        containers:
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8443
          - --metrics-secure=true
          - --leader-elect
          command:
          - /manager
          env:
          - name: OPERATOR_NAME
            value: rhdh-operator
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: RELATED_IMAGE_postgresql
            value: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
          - name: RELATED_IMAGE_backstage
            value: registry.redhat.io/rhdh/rhdh-hub-rhel9@sha256:0c76994fde2cd71471802d458b682ab652be5a0e291c3a2773cb524259ac79b2
          - name: OPERATOR_CONDITION_NAME
            value: rhdh-operator.v1.7.0
          image: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:df3cbd7b2d58a346bdf0e42148792e76075293a055e7a523505131ee7274f956
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          - containerPort: 8081
            name: health
            protocol: TCP
          - containerPort: 8443
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: health
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 20Mi
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /default-config
            name: default-config
          - mountPath: /plugin-deps
            name: plugin-deps
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: rhdh-controller-manager
        serviceAccountName: rhdh-controller-manager
        terminationGracePeriodSeconds: 10
        volumes:
        - configMap:
            defaultMode: 420
            name: rhdh-default-config
          name: default-config
        - configMap:
            defaultMode: 420
            name: rhdh-plugin-deps
            optional: true
          name: plugin-deps
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-10-23T11:09:30Z"
      lastUpdateTime: "2025-10-23T11:09:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-10-23T11:09:13Z"
      lastUpdateTime: "2025-10-23T11:09:30Z"
      message: ReplicaSet "rhdh-operator-6c8ffc4648" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
