---
apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: builder
    creationTimestamp: "2025-10-23T11:07:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"2e891ced-e3de-4254-924e-9193e717cbe1"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    name: builder-dockercfg-64tfj
    namespace: rhdh-orchestrator-infra
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: builder
      uid: 2e891ced-e3de-4254-924e-9193e717cbe1
    resourceVersion: "38579"
    uid: 76559604-a897-4972-9956-3163c913db77
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: default
    creationTimestamp: "2025-10-23T11:07:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"3e2e5988-31a4-47b2-803d-6edc62664cc5"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    name: default-dockercfg-qxql9
    namespace: rhdh-orchestrator-infra
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: default
      uid: 3e2e5988-31a4-47b2-803d-6edc62664cc5
    resourceVersion: "38576"
    uid: 70915da1-32aa-4e28-9ce7-65edc870d8f9
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    .dockercfg: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      openshift.io/internal-registry-auth-token.binding: bound
      openshift.io/internal-registry-auth-token.service-account: deployer
    creationTimestamp: "2025-10-23T11:07:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:.dockercfg: {}
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.binding: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_image-pull-secret-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:openshift.io/internal-registry-auth-token.service-account: {}
          f:ownerReferences:
            k:{"uid":"41b688d5-504b-40aa-842d-901ad69b3cbe"}: {}
        f:type: {}
      manager: openshift.io/image-registry-pull-secrets_service-account-controller
      operation: Apply
      time: "2025-10-23T11:07:11Z"
    name: deployer-dockercfg-5fqrv
    namespace: rhdh-orchestrator-infra
    ownerReferences:
    - apiVersion: v1
      kind: ServiceAccount
      name: deployer
      uid: 41b688d5-504b-40aa-842d-901ad69b3cbe
    resourceVersion: "38577"
    uid: 43266195-7876-458a-bd5d-4289887a1795
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    release: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T11:07:32Z"
    labels:
      modifiedAt: "1761217655"
      name: my-orchestrator-infra
      owner: helm
      status: deployed
      version: "1"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: Helm
      operation: Update
      time: "2025-10-23T11:07:35Z"
    name: sh.helm.release.v1.my-orchestrator-infra.v1
    namespace: rhdh-orchestrator-infra
    resourceVersion: "38762"
    uid: b82428b1-061c-4fae-847f-5395cf59c4e7
  type: helm.sh/release.v1
kind: SecretList
metadata:
  resourceVersion: "42066"
