apiVersion: v1
data:
  .dockercfg: [REDACTED]
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: default
  creationTimestamp: "2025-10-23T11:07:11Z"
  name: default-dockercfg-qxql9
  namespace: rhdh-orchestrator-infra
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: default
    uid: 3e2e5988-31a4-47b2-803d-6edc62664cc5
  resourceVersion: "38576"
  uid: 70915da1-32aa-4e28-9ce7-65edc870d8f9
type: kubernetes.io/dockercfg
