apiVersion: v1
data:
  .dockercfg: [REDACTED]
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: deployer
  creationTimestamp: "2025-09-11T20:42:17Z"
  name: deployer-dockercfg-bhb2c
  namespace: rhdh-orchestrator-infra
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: deployer
    uid: d12bad5e-5fd3-4265-a6d3-6209afd98fb9
  resourceVersion: "74526"
  uid: 09d3fdd0-b255-46e4-a5bd-6e4cf90e8fec
type: kubernetes.io/dockercfg
