---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T09:47:40Z"
    creationTimestamp: "2025-10-23T09:47:31Z"
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      helm.sh/chart: upstream-2.6.1
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:subsets: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:50:03Z"
    name: my-backstage-1-no-local-db-developer-hub
    namespace: my-ns-3
    resourceVersion: "2201"
    uid: 7eeffffa-d8a7-41db-b1fd-df63c7c4a993
  subsets:
  - notReadyAddresses:
    - ip: 10.42.3.8
      nodeName: k3d-local-1-server-0
      targetRef:
        kind: Pod
        name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
        namespace: my-ns-3
        uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
    ports:
    - name: http-backend
      port: 7007
      protocol: TCP
    - name: http-metrics
      port: 9464
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "4661"
