---
apiVersion: v1
items:
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:31Z"
  involvedObject:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root
    namespace: my-ns-3
    resourceVersion: "1791"
    uid: c5084423-a621-423a-96c8-79a7537b315c
  kind: Event
  lastTimestamp: "2025-10-23T09:47:31Z"
  message: waiting for pod my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    to be scheduled
  metadata:
    creationTimestamp: "2025-10-23T09:47:31Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root.187115c1d2223f1c
    namespace: my-ns-3
    resourceVersion: "1794"
    uid: e163ba3b-da16-4375-9205-e041037f446b
  reason: WaitForPodScheduled
  reportingComponent: persistentvolume-controller
  reportingInstance: ""
  source:
    component: persistentvolume-controller
  type: Normal
- apiVersion: v1
  count: 3
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:33Z"
  involvedObject:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root
    namespace: my-ns-3
    resourceVersion: "1803"
    uid: c5084423-a621-423a-96c8-79a7537b315c
  kind: Event
  lastTimestamp: "2025-10-23T09:47:35Z"
  message: Waiting for a volume to be created either by the external provisioner 'rancher.io/local-path'
    or manually by the system administrator. If volume creation is delayed, please
    verify that the provisioner is running and correctly registered.
  metadata:
    creationTimestamp: "2025-10-23T09:47:33Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:35Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root.187115c242fa72c0
    namespace: my-ns-3
    resourceVersion: "1812"
    uid: feba1824-d959-4052-a37f-d633dc486d69
  reason: ExternalProvisioning
  reportingComponent: persistentvolume-controller
  reportingInstance: ""
  source:
    component: persistentvolume-controller
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:33Z"
  involvedObject:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root
    namespace: my-ns-3
    resourceVersion: "1803"
    uid: c5084423-a621-423a-96c8-79a7537b315c
  kind: Event
  lastTimestamp: "2025-10-23T09:47:33Z"
  message: External provisioner is provisioning volume for claim "my-ns-3/my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root"
  metadata:
    creationTimestamp: "2025-10-23T09:47:33Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: local-path-provisioner
      operation: Update
      time: "2025-10-23T09:47:33Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root.187115c243393016
    namespace: my-ns-3
    resourceVersion: "1806"
    uid: 367f720d-fb2b-4751-b3da-1243fd8b507f
  reason: Provisioning
  reportingComponent: rancher.io/local-path_local-path-provisioner-5cf85fd84d-c7np4_a022ce66-b637-4734-a5d1-a9a76d8896bf
  reportingInstance: ""
  source:
    component: rancher.io/local-path_local-path-provisioner-5cf85fd84d-c7np4_a022ce66-b637-4734-a5d1-a9a76d8896bf
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:39Z"
  involvedObject:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root
    namespace: my-ns-3
    resourceVersion: "1803"
    uid: c5084423-a621-423a-96c8-79a7537b315c
  kind: Event
  lastTimestamp: "2025-10-23T09:47:39Z"
  message: Successfully provisioned volume pvc-c5084423-a621-423a-96c8-79a7537b315c
  metadata:
    creationTimestamp: "2025-10-23T09:47:39Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: local-path-provisioner
      operation: Update
      time: "2025-10-23T09:47:39Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root.187115c3ab08664b
    namespace: my-ns-3
    resourceVersion: "1830"
    uid: 7c34e0f4-e0e8-4666-9afe-fe5a755e3eb2
  reason: ProvisioningSucceeded
  reportingComponent: rancher.io/local-path_local-path-provisioner-5cf85fd84d-c7np4_a022ce66-b637-4734-a5d1-a9a76d8896bf
  reportingInstance: ""
  source:
    component: rancher.io/local-path_local-path-provisioner-5cf85fd84d-c7np4_a022ce66-b637-4734-a5d1-a9a76d8896bf
  type: Normal
- action: Scheduling
  apiVersion: v1
  eventTime: "2025-10-23T09:47:31.472959Z"
  firstTimestamp: null
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1789"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: null
  message: '0/4 nodes are available: waiting for ephemeral volume controller to create
    the persistentvolumeclaim "my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root".
    preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.'
  metadata:
    creationTimestamp: "2025-10-23T09:47:31Z"
    managedFields:
    - apiVersion: events.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:action: {}
        f:eventTime: {}
        f:note: {}
        f:reason: {}
        f:regarding: {}
        f:reportingController: {}
        f:reportingInstance: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115c1d1e61f07
    namespace: my-ns-3
    resourceVersion: "1792"
    uid: 0221829c-84db-4979-8fe3-2f1a6fd9be69
  reason: FailedScheduling
  reportingComponent: default-scheduler
  reportingInstance: default-scheduler-k3d-local-1-server-0
  source: {}
  type: Warning
- action: Binding
  apiVersion: v1
  eventTime: "2025-10-23T09:47:40.370510Z"
  firstTimestamp: null
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1795"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: null
  message: Successfully assigned my-ns-3/my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    to k3d-local-1-server-0
  metadata:
    creationTimestamp: "2025-10-23T09:47:40Z"
    managedFields:
    - apiVersion: events.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:action: {}
        f:eventTime: {}
        f:note: {}
        f:reason: {}
        f:regarding: {}
        f:reportingController: {}
        f:reportingInstance: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:40Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115c3e43bef2f
    namespace: my-ns-3
    resourceVersion: "1838"
    uid: 04b4e3ff-0d87-407c-8cab-d06650d0c0f8
  reason: Scheduled
  reportingComponent: default-scheduler
  reportingInstance: default-scheduler-k3d-local-1-server-0
  source: {}
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:40Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{install-dynamic-plugins}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T09:47:40Z"
  message: Pulling image "quay.io/rhdh/rhdh-hub-rhel9:latest"
  metadata:
    creationTimestamp: "2025-10-23T09:47:40Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:40Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115c3fbc18915
    namespace: my-ns-3
    resourceVersion: "1841"
    uid: d243454b-5c8a-4960-a281-beff7b331a64
  reason: Pulling
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:50:02Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{install-dynamic-plugins}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T09:50:02Z"
  message: 'Successfully pulled image "quay.io/rhdh/rhdh-hub-rhel9:latest" in 2m21.723s
    (2m21.723s including waiting). Image size: 1242208591 bytes.'
  metadata:
    creationTimestamp: "2025-10-23T09:50:02Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:50:02Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115e4fb235d6e
    namespace: my-ns-3
    resourceVersion: "2195"
    uid: 9cde6bcb-6139-4ea9-bdca-aacfac480278
  reason: Pulled
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:50:02Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{install-dynamic-plugins}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T09:50:02Z"
  message: Created container install-dynamic-plugins
  metadata:
    creationTimestamp: "2025-10-23T09:50:02Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:50:02Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115e4fdad0303
    namespace: my-ns-3
    resourceVersion: "2196"
    uid: c2d6c4af-b6a8-4051-b3ee-b500ff6cd7bf
  reason: Created
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:50:03Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{install-dynamic-plugins}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T09:50:03Z"
  message: Started container install-dynamic-plugins
  metadata:
    creationTimestamp: "2025-10-23T09:50:03Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:50:03Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115e519a069b0
    namespace: my-ns-3
    resourceVersion: "2198"
    uid: 982b2c05-77c1-42b6-8e34-2b68b30c64c9
  reason: Started
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Normal
- apiVersion: v1
  count: 101
  eventTime: null
  firstTimestamp: "2025-10-23T09:51:19Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{backstage-backend}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T10:12:42Z"
  message: Container image "quay.io/rhdh/rhdh-hub-rhel9:latest" already present on
    machine
  metadata:
    creationTimestamp: "2025-10-23T09:51:19Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T10:12:42Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115f6ef0df1c5
    namespace: my-ns-3
    resourceVersion: "4470"
    uid: d79337a5-5166-44f8-b6ef-e51bf2dbd4c0
  reason: Pulled
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Normal
- apiVersion: v1
  count: 11
  eventTime: null
  firstTimestamp: "2025-10-23T09:51:19Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{backstage-backend}
    kind: Pod
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
    namespace: my-ns-3
    resourceVersion: "1837"
    uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
  kind: Event
  lastTimestamp: "2025-10-23T09:53:27Z"
  message: 'Error: secret "my-backstage-1-no-local-db-postgresql" not found'
  metadata:
    creationTimestamp: "2025-10-23T09:51:19Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:53:27Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc.187115f6f0468e2f
    namespace: my-ns-3
    resourceVersion: "2579"
    uid: 217e06a4-f43c-4b31-8c0a-d4f018cad712
  reason: Failed
  reportingComponent: kubelet
  reportingInstance: k3d-local-1-server-0
  source:
    component: kubelet
    host: k3d-local-1-server-0
  type: Warning
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:31Z"
  involvedObject:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd
    namespace: my-ns-3
    resourceVersion: "1786"
    uid: b4be9838-6143-4d9e-8ce7-47bb35a10b64
  kind: Event
  lastTimestamp: "2025-10-23T09:47:31Z"
  message: 'Created pod: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc'
  metadata:
    creationTimestamp: "2025-10-23T09:47:31Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd.187115c1d1e076c3
    namespace: my-ns-3
    resourceVersion: "1790"
    uid: e0d6b9ef-7529-42cc-bf16-cd5eaff1c654
  reason: SuccessfulCreate
  reportingComponent: replicaset-controller
  reportingInstance: ""
  source:
    component: replicaset-controller
  type: Normal
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2025-10-23T09:47:31Z"
  involvedObject:
    apiVersion: apps/v1
    kind: Deployment
    name: my-backstage-1-no-local-db-developer-hub
    namespace: my-ns-3
    resourceVersion: "1785"
    uid: 5f522342-cc6b-4ea2-8003-1079fd881c39
  kind: Event
  lastTimestamp: "2025-10-23T09:47:31Z"
  message: Scaled up replica set my-backstage-1-no-local-db-developer-hub-7d94c7ccbd
    to 1
  metadata:
    creationTimestamp: "2025-10-23T09:47:31Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:source:
          f:component: {}
        f:type: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-developer-hub.187115c1d18c470e
    namespace: my-ns-3
    resourceVersion: "1787"
    uid: 1eeb2226-5071-4e63-b022-0ec0c3fff7a1
  reason: ScalingReplicaSet
  reportingComponent: deployment-controller
  reportingInstance: ""
  source:
    component: deployment-controller
  type: Normal
kind: EventList
metadata:
  resourceVersion: "4661"
