---
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k3d-local-1-server-0
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-23T09:47:31Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/selected-node: {}
            f:volume.kubernetes.io/storage-provisioner: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8db9458a-6d23-4388-bba6-e716acdb4b2c"}: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
          f:volumeName: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:47:39Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: k3s
      operation: Update
      subresource: status
      time: "2025-10-23T09:47:39Z"
    name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc-dynamic-plugins-root
    namespace: my-ns-3
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: my-backstage-1-no-local-db-developer-hub-7d94c7ccbd-gsknc
      uid: 8db9458a-6d23-4388-bba6-e716acdb4b2c
    resourceVersion: "1833"
    uid: c5084423-a621-423a-96c8-79a7537b315c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-c5084423-a621-423a-96c8-79a7537b315c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: PersistentVolumeClaimList
metadata:
  resourceVersion: "4661"
