---
apiVersion: v1
items:
- apiVersion: v1
  data:
    backend-secret: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1-no-local-db
      meta.helm.sh/release-namespace: my-ns-3
    creationTimestamp: "2025-10-23T09:47:31Z"
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      helm.sh/chart: backstage-4.6.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:backend-secret: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-auth
    namespace: my-ns-3
    resourceVersion: "1778"
    uid: 3f0d8640-593d-4403-beb0-0c6f72bdd073
  type: Opaque
- apiVersion: v1
  data:
    release: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T09:47:31Z"
    labels:
      modifiedAt: "1761212851"
      name: my-backstage-1-no-local-db
      owner: helm
      status: deployed
      version: "1"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: Helm
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: sh.helm.release.v1.my-backstage-1-no-local-db.v1
    namespace: my-ns-3
    resourceVersion: "1799"
    uid: 021fb91a-fa52-48f6-8a73-4bbe83451319
  type: helm.sh/release.v1
kind: SecretList
metadata:
  resourceVersion: "4661"
