---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1-no-local-db
      meta.helm.sh/release-namespace: my-ns-3
    creationTimestamp: "2025-10-23T09:47:31Z"
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      helm.sh/chart: upstream-2.6.1
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":7007,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":9464,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:47:31Z"
    name: my-backstage-1-no-local-db-developer-hub
    namespace: my-ns-3
    resourceVersion: "1782"
    uid: c2eb1f43-108b-40db-bd89-88e588a298cb
  spec:
    clusterIP: 10.43.229.128
    clusterIPs:
    - 10.43.229.128
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-backend
      port: 7007
      protocol: TCP
      targetPort: backend
    - name: http-metrics
      port: 9464
      protocol: TCP
      targetPort: 9464
    selector:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/name: developer-hub
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "4661"
