---
apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3NjEyMTI0ODgwHhcNMjUxMDIzMDk0MTI4WhcNMzUxMDIxMDk0MTI4
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3NjEyMTI0ODgwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAS/C3Lp2Ti3uT1D8toUxjfWqYnlL+XlM3XVwh6hKBsu
      rz/zOulFOQru61L0K9B50S66A7COZTq+0vUhjv9qhFq1o0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUGX8P3XVae09GYfnLAxXL
      YQF4qxkwCgYIKoZIzj0EAwIDSAAwRQIhAP6iRjQNjPQHDri1Zhxb6ct+P/3C01pR
      Ty0QdNlJe6/4AiBt6u/nooOaKY9tZKn2zp62BQcbUOaO/fScIKkpiz1tEQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-10-23T09:45:20Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:45:20Z"
    name: kube-root-ca.crt
    namespace: my-ns-2
    resourceVersion: "1543"
    uid: e418055b-a6be-407b-a177-7b6fb97f9de8
- apiVersion: v1
  data:
    app-config.yaml: |
      app:
        baseUrl: https://my-backstage-1.127.0.0.1.sslip.io
      auth:
        providers: {}
      backend:
        auth:
          externalAccess:
          - options:
              secret: ${BACKEND_SECRET}
              subject: legacy-default-config
            type: legacy
        baseUrl: https://my-backstage-1.127.0.0.1.sslip.io
        cors:
          origin: https://my-backstage-1.127.0.0.1.sslip.io
        database:
          connection:
            password: ${POSTGRESQL_ADMIN_PASSWORD}
            user: postgres
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:app-config.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:06Z"
    name: my-backstage-1-developer-hub-app-config
    namespace: my-ns-2
    resourceVersion: "1989"
    uid: 84211a04-fcb9-474b-934e-744656237d70
- apiVersion: v1
  data:
    dynamic-plugins.yaml: |
      includes:
      - dynamic-plugins.default.yaml
      plugins: []
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:dynamic-plugins.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:06Z"
    name: my-backstage-1-dynamic-plugins
    namespace: my-ns-2
    resourceVersion: "1990"
    uid: 141b9e6c-f550-453b-8a97-8c72f686541b
kind: ConfigMapList
metadata:
  resourceVersion: "4661"
