---
apiVersion: v1
items:
- apiVersion: v1
  data:
    backend-secret: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      helm.sh/chart: backstage-4.6.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:backend-secret: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:24Z"
    name: my-backstage-1-auth
    namespace: my-ns-2
    resourceVersion: "2118"
    uid: ac69c24d-0456-4c01-a810-60dafe47caaa
  type: Opaque
- apiVersion: v1
  data:
    password: [REDACTED]
    postgres-password: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 15.4.0
      helm.sh/chart: postgresql-12.10.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:password: {}
          f:postgres-password: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:06Z"
    name: my-backstage-1-postgresql
    namespace: my-ns-2
    resourceVersion: "1987"
    uid: 52367031-360b-4f57-a149-75a4178256ba
  type: Opaque
- apiVersion: v1
  data:
    host: [REDACTED]
    password: [REDACTED]
    port: [REDACTED]
    provider: [REDACTED]
    type: [REDACTED]
    uri: [REDACTED]
    username: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 15.4.0
      helm.sh/chart: postgresql-12.10.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:host: {}
          f:password: {}
          f:port: {}
          f:provider: {}
          f:type: {}
          f:uri: {}
          f:username: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:06Z"
    name: my-backstage-1-postgresql-svcbind-custom-user
    namespace: my-ns-2
    resourceVersion: "1986"
    uid: af5a646d-c734-4036-b846-05a19abd3c0c
  type: servicebinding.io/postgresql
- apiVersion: v1
  data:
    database: [REDACTED]
    host: [REDACTED]
    password: [REDACTED]
    port: [REDACTED]
    provider: [REDACTED]
    type: [REDACTED]
    uri: [REDACTED]
    username: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: my-backstage-1
      meta.helm.sh/release-namespace: my-ns-2
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 15.4.0
      helm.sh/chart: postgresql-12.10.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:database: {}
          f:host: {}
          f:password: {}
          f:port: {}
          f:provider: {}
          f:type: {}
          f:uri: {}
          f:username: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-10-23T09:49:06Z"
    name: my-backstage-1-postgresql-svcbind-postgres
    namespace: my-ns-2
    resourceVersion: "1988"
    uid: 89fb28e8-2edc-41da-83c6-20c9f9d766d5
  type: servicebinding.io/postgresql
- apiVersion: v1
  data:
    release: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T09:49:06Z"
    labels:
      modifiedAt: "1761212946"
      name: my-backstage-1
      owner: helm
      status: superseded
      version: "1"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: Helm
      operation: Update
      time: "2025-10-23T09:49:15Z"
    name: sh.helm.release.v1.my-backstage-1.v1
    namespace: my-ns-2
    resourceVersion: "2100"
    uid: 498d4443-fb6e-46cb-81da-c8a23de4bb89
  type: helm.sh/release.v1
- apiVersion: v1
  data:
    release: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T09:49:15Z"
    labels:
      modifiedAt: "1761212946"
      name: my-backstage-1
      owner: helm
      status: superseded
      version: "2"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: Helm
      operation: Update
      time: "2025-10-23T09:49:24Z"
    name: sh.helm.release.v1.my-backstage-1.v2
    namespace: my-ns-2
    resourceVersion: "2119"
    uid: 6bc3b2c7-2847-465d-815d-6417290de533
  type: helm.sh/release.v1
- apiVersion: v1
  data:
    release: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T09:49:24Z"
    labels:
      modifiedAt: "1761212946"
      name: my-backstage-1
      owner: helm
      status: deployed
      version: "3"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: Helm
      operation: Update
      time: "2025-10-23T09:49:25Z"
    name: sh.helm.release.v1.my-backstage-1.v3
    namespace: my-ns-2
    resourceVersion: "2120"
    uid: 49a1e145-0e01-47be-bce2-b9e3a31a6ce9
  type: helm.sh/release.v1
kind: SecretList
metadata:
  resourceVersion: "4661"
