apiVersion: v1
data:
  app-config.yaml: |
    app:
      baseUrl: https://my-backstage-1.127.0.0.1.sslip.io
    auth:
      providers: {}
    backend:
      auth:
        externalAccess:
        - options:
            secret: ${BACKEND_SECRET}
            subject: legacy-default-config
          type: legacy
      baseUrl: https://my-backstage-1.127.0.0.1.sslip.io
      cors:
        origin: https://my-backstage-1.127.0.0.1.sslip.io
      database:
        connection:
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          user: postgres
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1
    meta.helm.sh/release-namespace: my-ns-2
  creationTimestamp: "2025-10-23T09:49:06Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-backstage-1-developer-hub-app-config
  namespace: my-ns-2
  resourceVersion: "1989"
  uid: 84211a04-fcb9-474b-934e-744656237d70
