apiVersion: v1
data:
  dynamic-plugins.yaml: |
    includes:
    - dynamic-plugins.default.yaml
    plugins: []
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1
    meta.helm.sh/release-namespace: my-ns-2
  creationTimestamp: "2025-10-23T09:49:06Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-backstage-1-dynamic-plugins
  namespace: my-ns-2
  resourceVersion: "1990"
  uid: 141b9e6c-f550-453b-8a97-8c72f686541b
