---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhdh.redhat.com/v1alpha1",
          "kind": "Backstage",
          "metadata": {
            "labels": {
              "app.kubernetes.io/name": "backstage"
            },
            "name": "developer-hub"
          }
        },
        {
          "apiVersion": "rhdh.redhat.com/v1alpha2",
          "kind": "Backstage",
          "metadata": {
            "labels": {
              "app.kubernetes.io/name": "backstage"
            },
            "name": "developer-hub"
          }
        },
        {
          "apiVersion": "rhdh.redhat.com/v1alpha3",
          "kind": "Backstage",
          "metadata": {
            "labels": {
              "app.kubernetes.io/name": "backstage"
            },
            "name": "developer-hub"
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Developer Tools
    certified: "true"
    containerImage: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:df3cbd7b2d58a346bdf0e42148792e76075293a055e7a523505131ee7274f956
    createdAt: "2025-07-02T07:33:16Z"
    description: Red Hat Developer Hub is a Red Hat supported version of Backstage.
      It comes with pre-built plug-ins and configuration settings, supports use of
      an external database, and can help streamline the process of setting up a self-managed
      internal developer portal for adopters who are just starting out.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.0.36/23"],"mac_address":"0a:58:0a:81:00:24","gateway_ips":["10.129.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.129.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.129.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.129.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.129.0.1"}],"ip_address":"10.129.0.36/23","gateway_ip":"10.129.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.0.36"
          ],
          "mac": "0a:58:0a:81:00:24",
          "default": true,
          "dns": {}
      }]
    kubectl.kubernetes.io/default-container: manager
    olm.operatorGroup: rhdh-operator-wtgrm
    olm.operatorNamespace: rhdh-operator
    olm.targetNamespaces: ""
    openshift.io/scc: restricted-v2
    operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha1"}},{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha2"}},{"type":"olm.gvk","value":{"group":"rhdh.redhat.com","kind":"Backstage","version":"v1alpha3"}},{"type":"olm.package","value":{"packageName":"rhdh","version":"1.7.0"}}]}'
    operatorframework.io/suggested-namespace: rhdh-operator
    operators.openshift.io/valid-subscription: '["Red Hat Developer Hub"]'
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    repository: https://gitlab.cee.redhat.com/rhidp/rhdh/
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    skipRange: '>=1.0.0 <1.7.0'
    support: Red Hat
  creationTimestamp: "2025-10-23T11:09:13Z"
  generateName: rhdh-operator-6c8ffc4648-
  labels:
    app: rhdh-operator
    app.kubernetes.io/component: rhdh-operator
    control-plane: controller-manager
    pod-template-hash: 6c8ffc4648
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-1-166
    operation: Update
    subresource: status
    time: "2025-10-23T11:09:13Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:alm-examples: {}
          f:capabilities: {}
          f:categories: {}
          f:certified: {}
          f:containerImage: {}
          f:createdAt: {}
          f:description: {}
          f:features.operators.openshift.io/cnf: {}
          f:features.operators.openshift.io/cni: {}
          f:features.operators.openshift.io/csi: {}
          f:features.operators.openshift.io/disconnected: {}
          f:features.operators.openshift.io/fips-compliant: {}
          f:features.operators.openshift.io/proxy-aware: {}
          f:features.operators.openshift.io/tls-profiles: {}
          f:features.operators.openshift.io/token-auth-aws: {}
          f:features.operators.openshift.io/token-auth-azure: {}
          f:features.operators.openshift.io/token-auth-gcp: {}
          f:kubectl.kubernetes.io/default-container: {}
          f:olm.operatorGroup: {}
          f:olm.operatorNamespace: {}
          f:olm.targetNamespaces: {}
          f:operatorframework.io/properties: {}
          f:operatorframework.io/suggested-namespace: {}
          f:operators.openshift.io/valid-subscription: {}
          f:operators.operatorframework.io/builder: {}
          f:operators.operatorframework.io/project_layout: {}
          f:repository: {}
          f:skipRange: {}
          f:support: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:control-plane: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4f563765-4552-430e-ba88-813ed5e917dd"}: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution: {}
        f:automountServiceAccountToken: {}
        f:containers:
          k:{"name":"manager"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"OPERATOR_CONDITION_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"OPERATOR_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"RELATED_IMAGE_backstage"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"RELATED_IMAGE_postgresql"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8081,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":8443,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:ephemeral-storage: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:ephemeral-storage: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/default-config"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/plugin-deps"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsNonRoot: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"default-config"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"plugin-deps"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
              f:optional: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-10-23T11:09:13Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2025-10-23T11:09:13Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.129.0.36"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2025-10-23T11:09:30Z"
  name: rhdh-operator-6c8ffc4648-wnzzg
  namespace: rhdh-operator
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rhdh-operator-6c8ffc4648
    uid: 4f563765-4552-430e-ba88-813ed5e917dd
  resourceVersion: "39613"
  uid: d585dd39-baff-496c-85ac-174702b35fc9
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  automountServiceAccountToken: true
  containers:
  - args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=:8443
    - --metrics-secure=true
    - --leader-elect
    command:
    - /manager
    env:
    - name: OPERATOR_NAME
      value: rhdh-operator
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: RELATED_IMAGE_postgresql
      value: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
    - name: RELATED_IMAGE_backstage
      value: registry.redhat.io/rhdh/rhdh-hub-rhel9@sha256:0c76994fde2cd71471802d458b682ab652be5a0e291c3a2773cb524259ac79b2
    - name: OPERATOR_CONDITION_NAME
      value: rhdh-operator.v1.7.0
    image: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:df3cbd7b2d58a346bdf0e42148792e76075293a055e7a523505131ee7274f956
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: health
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: manager
    ports:
    - containerPort: 8081
      name: health
      protocol: TCP
    - containerPort: 8443
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: health
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 20Mi
        memory: 1Gi
      requests:
        cpu: 10m
        ephemeral-storage: 20Mi
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 1000870000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /default-config
      name: default-config
    - mountPath: /plugin-deps
      name: plugin-deps
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-b4ghg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: rhdh-controller-manager-dockercfg-txz4s
  nodeName: ip-10-0-1-166.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000870000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c30,c0
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: rhdh-controller-manager
  serviceAccountName: rhdh-controller-manager
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: rhdh-default-config
    name: default-config
  - configMap:
      defaultMode: 420
      name: rhdh-plugin-deps
      optional: true
    name: plugin-deps
  - name: kube-api-access-b4ghg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:09:18Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:09:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:09:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:09:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:09:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://355eae7bc074de20c49a4a1a3045c1545f7e96af25537c53ff3bfdf10bc9cbeb
    image: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:df3cbd7b2d58a346bdf0e42148792e76075293a055e7a523505131ee7274f956
    imageID: registry.redhat.io/rhdh/rhdh-rhel9-operator@sha256:72beabd2760976369736af8c22388b030603f9d503020aa581f4b8ec1c50c740
    lastState: {}
    name: manager
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-23T11:09:17Z"
    volumeMounts:
    - mountPath: /default-config
      name: default-config
    - mountPath: /plugin-deps
      name: plugin-deps
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-b4ghg
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.1.166
  hostIPs:
  - ip: 10.0.1.166
  phase: Running
  podIP: 10.129.0.36
  podIPs:
  - ip: 10.129.0.36
  qosClass: Burstable
  startTime: "2025-10-23T11:09:13Z"
