---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T11:08:19Z"
    creationTimestamp: "2025-10-23T11:08:14Z"
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1-no-local-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      helm.sh/chart: upstream-2.6.1
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-10-23T11:09:52Z"
    name: my-backstage-1-no-local-db-developer-hub
    namespace: my-ns-3
    resourceVersion: "39832"
    uid: 7ddeed27-dd98-49df-a8ea-f63a176ab28d
  subsets:
  - notReadyAddresses:
    - ip: 10.128.0.60
      nodeName: ip-10-0-1-102.ec2.internal
      targetRef:
        kind: Pod
        name: my-backstage-1-no-local-db-developer-hub-56fbb8cf48-gzwxj
        namespace: my-ns-3
        uid: fbe184ee-3313-4dcb-8c3c-c74b446c8b4c
    ports:
    - name: http-backend
      port: 7007
      protocol: TCP
    - name: http-metrics
      port: 9464
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "42051"
