config:
  route:
    enabled: false
  upstream:
    postgresql:
      enabled: false
hooks:
- events:
  - test
  kind: Pod
  last_run:
    completed_at: ""
    phase: ""
    started_at: ""
  manifest: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: "my-backstage-1-no-local-db-developer-hub-test-connection"
      labels:
        app.kubernetes.io/name: developer-hub
        helm.sh/chart: backstage-4.5.8
        app.kubernetes.io/instance: my-backstage-1-no-local-db
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: backstage
      annotations:
        helm.sh/hook: test
    spec:
      containers:
        - name: curl
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 10m
              memory: 20Mi
          livenessProbe:
            exec:
              command:
              - ls
              - /usr/bin/curl
          image: "quay.io/curl/curl:latest"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl --connect-timeout 5 --max-time 20 --retry 20 --retry-delay 10 --retry-max-time 60 --retry-all-errors my-backstage-1-no-local-db-developer-hub:7007
      restartPolicy: Never
  name: my-backstage-1-no-local-db-developer-hub-test-connection
  path: backstage/templates/tests/test-connection.yaml
info:
  deleted: ""
  description: Install complete
  first_deployed: "2025-09-11T23:23:13.416908664+02:00"
  last_deployed: "2025-09-11T23:23:13.416908664+02:00"
  status: deployed
manifest: "---\n# Source: backstage/templates/secrets.yaml\napiVersion: v1\nkind:
  Secret\nmetadata:\n  name: my-backstage-1-no-local-db-auth\n  namespace: \"my-ns-3\"\n
  \ labels:\n    app.kubernetes.io/name: developer-hub\n    helm.sh/chart: backstage-4.5.8\n
  \   app.kubernetes.io/instance: my-backstage-1-no-local-db\n    app.kubernetes.io/managed-by:
  Helm\n    app.kubernetes.io/component: backstage\n  annotations:\ntype: Opaque\ndata:\n
  \ backend-secret: \"Y2w3Tml4UzlaWWo4c2FyRVdKNGpkQVd2\"\n---\n# Source: backstage/charts/upstream/templates/app-config-configmap.yaml\napiVersion:
  v1\nkind: ConfigMap\nmetadata:\n  name: my-backstage-1-no-local-db-developer-hub-app-config\n
  \ namespace: \"my-ns-3\"\ndata:\n  app-config.yaml: |\n    app:\n      baseUrl:
  https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com\n    auth:\n
  \     providers: {}\n    backend:\n      auth:\n        externalAccess:\n        -
  options:\n            secret: ${BACKEND_SECRET}\n            subject: legacy-default-config\n
  \         type: legacy\n      baseUrl: https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com\n
  \     cors:\n        origin: https://my-backstage-1-no-local-db-developer-hub-my-ns-3.apps.example.com\n
  \     database:\n        connection:\n          password: ${POSTGRESQL_ADMIN_PASSWORD}\n
  \         user: postgres\n---\n# Source: backstage/templates/dynamic-plugins-configmap.yaml\napiVersion:
  v1\nkind: ConfigMap\nmetadata:\n  name: my-backstage-1-no-local-db-dynamic-plugins\ndata:\n
  \ dynamic-plugins.yaml: |\n    includes:\n    - dynamic-plugins.default.yaml\n    plugins:
  []\n---\n# Source: backstage/charts/upstream/templates/service.yaml\napiVersion:
  v1\nkind: Service\nmetadata:\n  name: my-backstage-1-no-local-db-developer-hub\n
  \ namespace: \"my-ns-3\" \n  labels:\n    app.kubernetes.io/name: developer-hub\n
  \   helm.sh/chart: upstream-2.6.1\n    app.kubernetes.io/instance: my-backstage-1-no-local-db\n
  \   app.kubernetes.io/managed-by: Helm\n    app.kubernetes.io/component: backstage\nspec:\n
  \ type: ClusterIP\n  sessionAffinity: None\n  ports:\n    - name: http-backend\n
  \     port: 7007\n      targetPort: backend\n      protocol: TCP\n      nodePort:
  null\n    - name: http-metrics\n      port: 9464\n      targetPort: 9464  \n  selector:\n
  \   app.kubernetes.io/name: developer-hub\n    app.kubernetes.io/instance: my-backstage-1-no-local-db\n
  \   app.kubernetes.io/component: backstage\n---\n# Source: backstage/charts/upstream/templates/backstage-deployment.yaml\napiVersion:
  apps/v1\nkind: Deployment\nmetadata:\n  name: my-backstage-1-no-local-db-developer-hub\n
  \ namespace: \"my-ns-3\"\n  labels: \n    app.kubernetes.io/name: developer-hub\n
  \   helm.sh/chart: upstream-2.6.1\n    app.kubernetes.io/instance: my-backstage-1-no-local-db\n
  \   app.kubernetes.io/managed-by: Helm\n    app.kubernetes.io/component: backstage\n
  \ annotations:\nspec:\n  replicas: 1\n  revisionHistoryLimit: 10\n  selector:\n
  \   matchLabels:\n      app.kubernetes.io/name: developer-hub\n      app.kubernetes.io/instance:
  my-backstage-1-no-local-db\n      app.kubernetes.io/component: backstage\n  template:\n
  \   metadata:\n      labels:\n        app.kubernetes.io/name: developer-hub\n        helm.sh/chart:
  upstream-2.6.1\n        app.kubernetes.io/instance: my-backstage-1-no-local-db\n
  \       app.kubernetes.io/managed-by: Helm\n        app.kubernetes.io/component:
  backstage\n      annotations:\n        checksum/app-config: 17ff9d7d3ac62ad797cdf103fb3f3be8827f06b3e100a1b934551c5bf52b0093\n
  \       checksum/dynamic-plugins: 'f1f9a92f14a31362d7eb30e67ac1458faf1c685765610f93a8967194d8bc1a5f'\n
  \   spec:\n      serviceAccountName: default\n      volumes:\n        - ephemeral:\n
  \           volumeClaimTemplate:\n              spec:\n                accessModes:\n
  \               - ReadWriteOnce\n                resources:\n                  requests:\n
  \                   storage: 5Gi\n          name: dynamic-plugins-root\n        -
  configMap:\n            defaultMode: 420\n            name: 'my-backstage-1-no-local-db-dynamic-plugins'\n
  \           optional: true\n          name: dynamic-plugins\n        - name: dynamic-plugins-npmrc\n
  \         secret:\n            defaultMode: 420\n            optional: true\n            secretName:
  'my-backstage-1-no-local-db-dynamic-plugins-npmrc'\n        - name: dynamic-plugins-registry-auth\n
  \         secret:\n            defaultMode: 416\n            optional: true\n            secretName:
  'my-backstage-1-no-local-db-dynamic-plugins-registry-auth'\n        - emptyDir:
  {}\n          name: npmcacache\n        - emptyDir: {}\n          name: temp\n        -
  name: backstage-app-config\n          configMap:\n            name: my-backstage-1-no-local-db-developer-hub-app-config\n
  \     \n      initContainers:\n        - command:\n          - ./install-dynamic-plugins.sh\n
  \         - /dynamic-plugins-root\n          env:\n          - name: NPM_CONFIG_USERCONFIG\n
  \           value: /opt/app-root/src/.npmrc.dynamic-plugins\n          - name: MAX_ENTRY_SIZE\n
  \           value: \"30000000\"\n          image: 'quay.io/rhdh/rhdh-hub-rhel9:latest'\n
  \         imagePullPolicy: Always\n          name: install-dynamic-plugins\n          resources:\n
  \           limits:\n              cpu: 1000m\n              ephemeral-storage:
  5Gi\n              memory: 2.5Gi\n            requests:\n              cpu: 250m\n
  \             memory: 256Mi\n          securityContext:\n            allowPrivilegeEscalation:
  false\n            capabilities:\n              drop:\n              - ALL\n            readOnlyRootFilesystem:
  true\n            runAsNonRoot: true\n            seccompProfile:\n              type:
  RuntimeDefault\n          volumeMounts:\n          - mountPath: /dynamic-plugins-root\n
  \           name: dynamic-plugins-root\n          - mountPath: /opt/app-root/src/dynamic-plugins.yaml\n
  \           name: dynamic-plugins\n            readOnly: true\n            subPath:
  dynamic-plugins.yaml\n          - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins\n
  \           name: dynamic-plugins-npmrc\n            readOnly: true\n            subPath:
  .npmrc\n          - mountPath: /opt/app-root/src/.config/containers\n            name:
  dynamic-plugins-registry-auth\n            readOnly: true\n          - mountPath:
  /opt/app-root/src/.npm/_cacache\n            name: npmcacache\n          - mountPath:
  /tmp\n            name: temp\n          workingDir: /opt/app-root/src\n      containers:\n
  \       - name: backstage-backend\n          image: quay.io/rhdh/rhdh-hub-rhel9:latest\n
  \         imagePullPolicy: \"Always\"\n          securityContext:\n            allowPrivilegeEscalation:
  false\n            capabilities:\n              drop:\n              - ALL\n            readOnlyRootFilesystem:
  true\n            runAsNonRoot: true\n            seccompProfile:\n              type:
  RuntimeDefault\n          args:\n            - \"--config\"\n            - \"dynamic-plugins-root/app-config.dynamic-plugins.yaml\"\n
  \           - \"--config\"\n            - \"/opt/app-root/src/app-config-from-configmap.yaml\"\n
  \         resources:\n            limits:\n              cpu: 1000m\n              ephemeral-storage:
  5Gi\n              memory: 2.5Gi\n            requests:\n              cpu: 250m\n
  \             memory: 1Gi\n          readinessProbe:\n            failureThreshold:
  3\n            httpGet:\n              path: /.backstage/health/v1/readiness\n              port:
  backend\n              scheme: HTTP\n            periodSeconds: 10\n            successThreshold:
  2\n            timeoutSeconds: 4\n          livenessProbe:\n            failureThreshold:
  3\n            httpGet:\n              path: /.backstage/health/v1/liveness\n              port:
  backend\n              scheme: HTTP\n            periodSeconds: 10\n            successThreshold:
  1\n            timeoutSeconds: 4\n          startupProbe:\n            failureThreshold:
  3\n            httpGet:\n              path: /.backstage/health/v1/liveness\n              port:
  backend\n              scheme: HTTP\n            initialDelaySeconds: 30\n            periodSeconds:
  20\n            successThreshold: 1\n            timeoutSeconds: 4\n          env:\n
  \           - name: APP_CONFIG_backend_listen_port\n              value: \"7007\"\n
  \           - name: BACKEND_SECRET\n              valueFrom:\n                secretKeyRef:\n
  \                 key: backend-secret\n                  name: 'my-backstage-1-no-local-db-auth'\n
  \           - name: POSTGRESQL_ADMIN_PASSWORD\n              valueFrom:\n                secretKeyRef:\n
  \                 key: postgres-password\n                  name: 'my-backstage-1-no-local-db-postgresql'\n
  \         ports:\n            - name: backend\n              containerPort: 7007\n
  \             protocol: TCP\n          volumeMounts:\n            - name: backstage-app-config\n
  \             mountPath: \"/opt/app-root/src/app-config-from-configmap.yaml\"\n
  \             subPath: app-config.yaml\n            - mountPath: /opt/app-root/src/dynamic-plugins-root\n
  \             name: dynamic-plugins-root\n            - mountPath: /tmp\n              name:
  temp\n---\n# Source: backstage/templates/tests/test-secret.yaml\n# RHDHBUGS-1893:
  test-only option to inject a user-provided dynamic plugins npmrc secret.\n# Doing
  it this way because the secret name is dynamic and depends on the release name.\n"
name: my-backstage-1-no-local-db
namespace: my-ns-3
version: 1
