apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rhdh-operator","control-plane":"controller-manager"},"name":"rhdh-operator","namespace":"rhdh-operator"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rhdh-operator"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container":"manager"},"labels":{"app":"rhdh-operator","app.kubernetes.io/component":"rhdh-operator","control-plane":"controller-manager"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}]}}},"automountServiceAccountToken":true,"containers":[{"args":["--health-probe-bind-address=:8081","--metrics-bind-address=:8443","--metrics-secure=true","--leader-elect"],"command":["/manager"],"env":[{"name":"OPERATOR_NAME","value":"rhdh-operator"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"RELATED_IMAGE_postgresql","value":"quay.io/fedora/postgresql-15:latest"},{"name":"RELATED_IMAGE_backstage","value":"quay.io/rhdh/rhdh-hub-rhel9:next"}],"image":"quay.io/rhdh/rhdh-rhel9-operator:1.8","livenessProbe":{"httpGet":{"path":"/healthz","port":"health"},"initialDelaySeconds":15,"periodSeconds":20},"name":"manager","ports":[{"containerPort":8081,"name":"health"},{"containerPort":8443,"name":"metrics"}],"readinessProbe":{"httpGet":{"path":"/readyz","port":"health"},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","ephemeral-storage":"20Mi","memory":"1Gi"},"requests":{"cpu":"10m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true},"volumeMounts":[{"mountPath":"/default-config","name":"default-config"},{"mountPath":"/plugin-deps","name":"plugin-deps"}]}],"securityContext":{"runAsNonRoot":true},"serviceAccountName":"rhdh-controller-manager","terminationGracePeriodSeconds":10,"volumes":[{"configMap":{"name":"rhdh-default-config"},"name":"default-config"},{"configMap":{"name":"rhdh-plugin-deps","optional":true},"name":"plugin-deps"}]}}}}
    creationTimestamp: "2025-09-11T21:22:42Z"
    generation: 1
    labels:
      app: rhdh-operator
      control-plane: controller-manager
    name: rhdh-operator
    namespace: rhdh-operator
    resourceVersion: "28566"
    uid: 7a2045af-5f26-401e-825c-92000cf71473
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: rhdh-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: manager
        creationTimestamp: null
        labels:
          app: rhdh-operator
          app.kubernetes.io/component: rhdh-operator
          control-plane: controller-manager
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
        automountServiceAccountToken: true
        containers:
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8443
          - --metrics-secure=true
          - --leader-elect
          command:
          - /manager
          env:
          - name: OPERATOR_NAME
            value: rhdh-operator
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: RELATED_IMAGE_postgresql
            value: quay.io/fedora/postgresql-15:latest
          - name: RELATED_IMAGE_backstage
            value: quay.io/rhdh/rhdh-hub-rhel9:next
          image: quay.io/rhdh/rhdh-rhel9-operator:1.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          - containerPort: 8081
            name: health
            protocol: TCP
          - containerPort: 8443
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: health
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 20Mi
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /default-config
            name: default-config
          - mountPath: /plugin-deps
            name: plugin-deps
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: rhdh-controller-manager
        serviceAccountName: rhdh-controller-manager
        terminationGracePeriodSeconds: 10
        volumes:
        - configMap:
            defaultMode: 420
            name: rhdh-default-config
          name: default-config
        - configMap:
            defaultMode: 420
            name: rhdh-plugin-deps
            optional: true
          name: plugin-deps
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-09-11T21:23:02Z"
      lastUpdateTime: "2025-09-11T21:23:02Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-09-11T21:22:42Z"
      lastUpdateTime: "2025-09-11T21:23:02Z"
      message: ReplicaSet "rhdh-operator-7c4fb58967" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
