---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.0.40/23"],"mac_address":"0a:58:0a:81:00:28","gateway_ips":["10.129.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.129.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.129.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.129.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.129.0.1"}],"ip_address":"10.129.0.40/23","gateway_ip":"10.129.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.0.40"
          ],
          "mac": "0a:58:0a:81:00:28",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2025-10-23T11:12:31Z"
  generateName: backstage-psql-my-developer-hub-op-
  labels:
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: backstage-psql-my-developer-hub-op-7fcc657f45
    rhdh.redhat.com/app: backstage-psql-my-developer-hub-op
    statefulset.kubernetes.io/pod-name: backstage-psql-my-developer-hub-op-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:apps.kubernetes.io/pod-index: {}
          f:controller-revision-hash: {}
          f:rhdh.redhat.com/app: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"55360e8e-14bf-4449-bf87-88fc67722102"}: {}
      f:spec:
        f:automountServiceAccountToken: {}
        f:containers:
          k:{"name":"postgresql"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"PGDATA"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POSTGRESQL_PORT_NUMBER"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POSTGRESQL_VOLUME_DIR"}:
                .: {}
                f:name: {}
                f:value: {}
            f:envFrom: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":5432,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:ephemeral-storage: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:ephemeral-storage: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:runAsGroup: {}
              f:runAsNonRoot: {}
              f:seccompProfile:
                .: {}
                f:type: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/dev/shm"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/pgsql/data"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"data"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"dshm"}:
            .: {}
            f:emptyDir:
              .: {}
              f:medium: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-10-23T11:12:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: ip-10-0-1-166
    operation: Update
    subresource: status
    time: "2025-10-23T11:12:34Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2025-10-23T11:12:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.129.0.40"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2025-10-23T11:14:09Z"
  name: backstage-psql-my-developer-hub-op-0
  namespace: my-ns
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: backstage-psql-my-developer-hub-op
    uid: 55360e8e-14bf-4449-bf87-88fc67722102
  resourceVersion: "40834"
  uid: f789d068-ad7d-41c5-995c-a5cdbf9f7406
spec:
  automountServiceAccountToken: false
  containers:
  - env:
    - name: POSTGRESQL_PORT_NUMBER
      value: "5432"
    - name: POSTGRESQL_VOLUME_DIR
      value: /var/lib/pgsql/data
    - name: PGDATA
      value: /var/lib/pgsql/data/userdata
    envFrom:
    - secretRef:
        name: backstage-psql-secret-my-developer-hub-op
    image: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: postgresql
    ports:
    - containerPort: 5432
      name: tcp-postgresql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - -e
        - |
          exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 250m
        ephemeral-storage: 20Mi
        memory: 1Gi
      requests:
        cpu: 250m
        ephemeral-storage: 20Mi
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 0
      runAsNonRoot: true
      runAsUser: 1000800000
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /var/lib/pgsql/data
      name: data
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: backstage-psql-my-developer-hub-op-0
  imagePullSecrets:
  - name: default-dockercfg-k4hmt
  nodeName: ip-10-0-1-166.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000800000
    seLinuxOptions:
      level: s0:c28,c22
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  subdomain: backstage-psql-my-developer-hub-op
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-backstage-psql-my-developer-hub-op-0
  - emptyDir:
      medium: Memory
    name: dshm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:13:58Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:12:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:14:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:14:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-23T11:12:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://475b1dfae661c97c66357234b4532d629d28c2aa3a83ee9593b049b6faf9b74b
    image: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
    imageID: registry.redhat.io/rhel9/postgresql-15@sha256:0d5db57d495484a4516aab577c1144b139b8b98847500c55e67e35652ca744d0
    lastState: {}
    name: postgresql
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-23T11:13:57Z"
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /var/lib/pgsql/data
      name: data
  hostIP: 10.0.1.166
  hostIPs:
  - ip: 10.0.1.166
  phase: Running
  podIP: 10.129.0.40
  podIPs:
  - ip: 10.129.0.40
  qosClass: Burstable
  startTime: "2025-10-23T11:12:34Z"
