apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.0.39/23"],"mac_address":"0a:58:0a:80:00:27","gateway_ips":["10.128.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.128.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.0.1"}],"ip_address":"10.128.0.39/23","gateway_ip":"10.128.0.1","role":"primary"}}'
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "ovn-kubernetes",
            "interface": "eth0",
            "ips": [
                "10.128.0.39"
            ],
            "mac": "0a:58:0a:80:00:27",
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: restricted-v2
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    creationTimestamp: "2025-09-11T20:50:02Z"
    generateName: backstage-psql-my-developer-hub-
    labels:
      apps.kubernetes.io/pod-index: "0"
      controller-revision-hash: backstage-psql-my-developer-hub-79577dcdbf
      rhdh.redhat.com/app: backstage-psql-my-developer-hub
      statefulset.kubernetes.io/pod-name: backstage-psql-my-developer-hub-0
    name: backstage-psql-my-developer-hub-0
    namespace: my-ns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: backstage-psql-my-developer-hub
      uid: ffb6b73c-7e0b-4442-93be-ba2790bfc255
    resourceVersion: "77994"
    uid: 9c571cf2-1bb2-4b9e-812c-0aaa379059a3
  spec:
    automountServiceAccountToken: false
    containers:
    - env:
      - name: POSTGRESQL_PORT_NUMBER
        value: "5432"
      - name: POSTGRESQL_VOLUME_DIR
        value: /var/lib/pgsql/data
      - name: PGDATA
        value: /var/lib/pgsql/data/userdata
      envFrom:
      - secretRef:
          name: backstage-psql-secret-my-developer-hub
      image: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
        failureThreshold: 6
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: postgresql
      ports:
      - containerPort: 5432
        name: tcp-postgresql
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - -e
          - |
            exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
        failureThreshold: 6
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        limits:
          cpu: 250m
          ephemeral-storage: 20Mi
          memory: 1Gi
        requests:
          cpu: 250m
          ephemeral-storage: 20Mi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 1000800000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /var/lib/pgsql/data
        name: data
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: backstage-psql-my-developer-hub-0
    imagePullSecrets:
    - name: default-dockercfg-hbnf5
    nodeName: ip-10-0-1-180.ec2.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000800000
      seLinuxOptions:
        level: s0:c28,c22
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: default
    serviceAccountName: default
    subdomain: backstage-psql-my-developer-hub
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-backstage-psql-my-developer-hub-0
    - emptyDir:
        medium: Memory
      name: dshm
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T20:50:15Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T20:50:05Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T20:50:27Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T20:50:27Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-09-11T20:50:05Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://a309f21ca0a3ebc27bc805550405b2cf808972a772dcc80742c01ac6cba1d103
      image: registry.redhat.io/rhel9/postgresql-15@sha256:b8266c990ed58a483f7dc57406525d0910b694d65e6a7d00924231fe3d8f039e
      imageID: registry.redhat.io/rhel9/postgresql-15@sha256:0d5db57d495484a4516aab577c1144b139b8b98847500c55e67e35652ca744d0
      lastState: {}
      name: postgresql
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-09-11T20:50:15Z"
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /var/lib/pgsql/data
        name: data
    hostIP: 10.0.1.180
    hostIPs:
    - ip: 10.0.1.180
    phase: Running
    podIP: 10.128.0.39
    podIPs:
    - ip: 10.128.0.39
    qosClass: Burstable
    startTime: "2025-09-11T20:50:05Z"
kind: List
metadata:
  resourceVersion: ""
