---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.42.2.12
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: k3d-local-1-agent-2
    targetRef:
      kind: Pod
      name: my-backstage-1-developer-hub-5687c46b88-z4jt9
      namespace: my-ns-2
      uid: 5a6d9115-becb-4ba5-bf0b-561d3a6952ba
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T09:52:43Z"
    creationTimestamp: "2025-10-23T09:49:06Z"
    generateName: my-backstage-1-developer-hub-
    generation: 3
    labels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: developer-hub
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: upstream-2.6.1
      kubernetes.io/service-name: my-backstage-1-developer-hub
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"edf99457-a93f-4050-bc83-05eebd6dae63"}: {}
        f:ports: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:52:43Z"
    name: my-backstage-1-developer-hub-fmdmb
    namespace: my-ns-2
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: my-backstage-1-developer-hub
      uid: edf99457-a93f-4050-bc83-05eebd6dae63
    resourceVersion: "2498"
    uid: 011f3601-cf91-43ec-963b-2874f42b96b0
  ports:
  - name: http-backend
    port: 7007
    protocol: TCP
  - name: http-metrics
    port: 9464
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.42.0.6
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: k3d-local-1-agent-0
    targetRef:
      kind: Pod
      name: my-backstage-1-postgresql-0
      namespace: my-ns-2
      uid: 9b135f55-eee5-4883-b9d5-c4a313f835f0
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T09:49:44Z"
    creationTimestamp: "2025-10-23T09:49:06Z"
    generateName: my-backstage-1-postgresql-
    generation: 3
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 15.4.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: postgresql-12.10.0
      kubernetes.io/service-name: my-backstage-1-postgresql
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"508b29e2-abdb-402c-8b0a-4f856d36e831"}: {}
        f:ports: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:49:44Z"
    name: my-backstage-1-postgresql-gkb4d
    namespace: my-ns-2
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: my-backstage-1-postgresql
      uid: 508b29e2-abdb-402c-8b0a-4f856d36e831
    resourceVersion: "2163"
    uid: 2e280a03-e6ac-43f8-9ea4-1b11fe332b53
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.42.0.6
    conditions:
      ready: true
      serving: true
      terminating: false
    hostname: my-backstage-1-postgresql-0
    nodeName: k3d-local-1-agent-0
    targetRef:
      kind: Pod
      name: my-backstage-1-postgresql-0
      namespace: my-ns-2
      uid: 9b135f55-eee5-4883-b9d5-c4a313f835f0
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-10-23T09:49:44Z"
    creationTimestamp: "2025-10-23T09:49:06Z"
    generateName: my-backstage-1-postgresql-hl-
    generation: 3
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: my-backstage-1
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 15.4.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: postgresql-12.10.0
      kubernetes.io/service-name: my-backstage-1-postgresql-hl
      service.kubernetes.io/headless: ""
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:service.kubernetes.io/headless: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8897040d-9b54-4731-8417-da3d3ec54497"}: {}
        f:ports: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:49:44Z"
    name: my-backstage-1-postgresql-hl-tnqlh
    namespace: my-ns-2
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: my-backstage-1-postgresql-hl
      uid: 8897040d-9b54-4731-8417-da3d3ec54497
    resourceVersion: "2164"
    uid: 6a132416-9a9c-49dd-884d-5bb45947698e
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "4661"
