apiVersion: v1
data:
  database: [REDACTED]
  host: [REDACTED]
  password: [REDACTED]
  port: [REDACTED]
  provider: [REDACTED]
  type: [REDACTED]
  uri: [REDACTED]
  username: [REDACTED]
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1
    meta.helm.sh/release-namespace: my-ns-2
  creationTimestamp: "2025-10-23T09:49:06Z"
  labels:
    app.kubernetes.io/instance: my-backstage-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.10.0
  name: my-backstage-1-postgresql-svcbind-postgres
  namespace: my-ns-2
  resourceVersion: "1988"
  uid: 89fb28e8-2edc-41da-83c6-20c9f9d766d5
type: servicebinding.io/postgresql
