apiVersion: v1
data:
  backend-secret: [REDACTED]
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1
    meta.helm.sh/release-namespace: my-ns-2
  creationTimestamp: "2025-10-23T09:49:06Z"
  labels:
    app.kubernetes.io/component: backstage
    app.kubernetes.io/instance: my-backstage-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: developer-hub
    helm.sh/chart: backstage-4.6.0
  name: my-backstage-1-auth
  namespace: my-ns-2
  resourceVersion: "2118"
  uid: ac69c24d-0456-4c01-a810-60dafe47caaa
type: Opaque
