apiVersion: v1
data:
  password: [REDACTED]
  postgres-password: [REDACTED]
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-backstage-1
    meta.helm.sh/release-namespace: my-ns-2
  creationTimestamp: "2025-09-11T21:31:37Z"
  labels:
    app.kubernetes.io/instance: my-backstage-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.10.0
  name: my-backstage-1-postgresql
  namespace: my-ns-2
  resourceVersion: "29596"
  uid: 68dbacfb-c194-4b75-9100-e632e5176ff9
type: Opaque
