---
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k3d-local-1-agent-2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-23T09:44:56Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/selected-node: {}
            f:volume.kubernetes.io/storage-provisioner: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"984806e0-1225-4230-81ad-676b8bfcc9da"}: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
          f:volumeName: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:45:03Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: k3s
      operation: Update
      subresource: status
      time: "2025-10-23T09:45:03Z"
    name: backstage-my-rhdh-6457df4994-r2cps-dynamic-plugins-root
    namespace: my-ns
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: backstage-my-rhdh-6457df4994-r2cps
      uid: 984806e0-1225-4230-81ad-676b8bfcc9da
    resourceVersion: "1500"
    uid: c90434e0-9a17-48d8-891b-3db7da143200
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-c90434e0-9a17-48d8-891b-3db7da143200
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k3d-local-1-agent-1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-23T09:44:56Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      rhdh.redhat.com/app: backstage-psql-my-rhdh
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/selected-node: {}
            f:volume.kubernetes.io/storage-provisioner: {}
          f:labels:
            .: {}
            f:rhdh.redhat.com/app: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
          f:volumeName: {}
      manager: k3s
      operation: Update
      time: "2025-10-23T09:45:01Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: k3s
      operation: Update
      subresource: status
      time: "2025-10-23T09:45:01Z"
    name: data-backstage-psql-my-rhdh-0
    namespace: my-ns
    resourceVersion: "1485"
    uid: e9eb647d-0dbe-4d7e-95c0-94704ff22637
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-e9eb647d-0dbe-4d7e-95c0-94704ff22637
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: PersistentVolumeClaimList
metadata:
  resourceVersion: "4661"
