---
apiVersion: v1
items:
- apiVersion: v1
  data:
    .npmrc: [REDACTED]
  kind: Secret
  metadata:
    annotations:
      rhdh.redhat.com/containers: install-dynamic-plugins
      rhdh.redhat.com/mount-path: /opt/app-root/src/.npmrc.dynamic-plugins
    creationTimestamp: "2025-10-23T09:44:56Z"
    labels:
      app.kubernetes.io/instance: my-rhdh
      app.kubernetes.io/name: backstage
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:rhdh.redhat.com/containers: {}
            f:rhdh.redhat.com/mount-path: {}
          f:labels:
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
          f:ownerReferences:
            k:{"uid":"66af0070-357e-4be2-a571-6706ec838dcb"}: {}
        f:stringData:
          f:.npmrc: {}
        f:type: {}
      manager: backstage-controller
      operation: Apply
      time: "2025-10-23T09:44:56Z"
    name: backstage-files-my-rhdh
    namespace: my-ns
    ownerReferences:
    - apiVersion: rhdh.redhat.com/v1alpha4
      blockOwnerDeletion: true
      controller: true
      kind: Backstage
      name: my-rhdh
      uid: 66af0070-357e-4be2-a571-6706ec838dcb
    resourceVersion: "1415"
    uid: ff215f7d-d7a9-47d2-a45f-f51a60e67553
  type: Opaque
- apiVersion: v1
  data:
    POSTGRES_HOST: [REDACTED]
    POSTGRES_PASSWORD: [REDACTED]
    POSTGRES_PORT: [REDACTED]
    POSTGRES_USER: [REDACTED]
    POSTGRESQL_ADMIN_PASSWORD: [REDACTED]
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-23T09:44:56Z"
    labels:
      app.kubernetes.io/instance: my-rhdh
      app.kubernetes.io/name: backstage
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:POSTGRES_HOST: {}
          f:POSTGRES_PASSWORD: {}
          f:POSTGRES_PORT: {}
          f:POSTGRES_USER: {}
          f:POSTGRESQL_ADMIN_PASSWORD: {}
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"66af0070-357e-4be2-a571-6706ec838dcb"}: {}
        f:type: {}
      manager: backstage-controller
      operation: Update
      time: "2025-10-23T09:44:56Z"
    name: backstage-psql-secret-my-rhdh
    namespace: my-ns
    ownerReferences:
    - apiVersion: rhdh.redhat.com/v1alpha4
      blockOwnerDeletion: true
      controller: true
      kind: Backstage
      name: my-rhdh
      uid: 66af0070-357e-4be2-a571-6706ec838dcb
    resourceVersion: "1410"
    uid: 747de2cc-6532-4ddc-83f5-5d4eaa221df2
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "4661"
