---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-23T09:44:56Z"
    labels:
      app.kubernetes.io/instance: my-rhdh
      app.kubernetes.io/name: backstage
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
          f:ownerReferences:
            k:{"uid":"66af0070-357e-4be2-a571-6706ec838dcb"}: {}
        f:spec:
          f:ports:
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:targetPort: {}
            k:{"port":9464,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:type: {}
      manager: backstage-controller
      operation: Apply
      time: "2025-10-23T09:44:56Z"
    name: backstage-my-rhdh
    namespace: my-ns
    ownerReferences:
    - apiVersion: rhdh.redhat.com/v1alpha4
      blockOwnerDeletion: true
      controller: true
      kind: Backstage
      name: my-rhdh
      uid: 66af0070-357e-4be2-a571-6706ec838dcb
    resourceVersion: "1419"
    uid: ec30de03-44bd-4b29-a2f1-a3e5fd348866
  spec:
    clusterIP: 10.43.8.136
    clusterIPs:
    - 10.43.8.136
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-backend
      nodePort: 30704
      port: 80
      protocol: TCP
      targetPort: backend
    - name: http-metrics
      nodePort: 32526
      port: 9464
      protocol: TCP
      targetPort: 9464
    selector:
      rhdh.redhat.com/app: backstage-my-rhdh
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-23T09:44:56Z"
    labels:
      app.kubernetes.io/instance: my-rhdh
      app.kubernetes.io/name: backstage
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
          f:ownerReferences:
            k:{"uid":"66af0070-357e-4be2-a571-6706ec838dcb"}: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            k:{"port":5432,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:targetPort: {}
          f:selector: {}
      manager: backstage-controller
      operation: Apply
      time: "2025-10-23T09:44:56Z"
    name: backstage-psql-my-rhdh
    namespace: my-ns
    ownerReferences:
    - apiVersion: rhdh.redhat.com/v1alpha4
      blockOwnerDeletion: true
      controller: true
      kind: Backstage
      name: my-rhdh
      uid: 66af0070-357e-4be2-a571-6706ec838dcb
    resourceVersion: "1411"
    uid: b271ce51-e768-479c-8642-c4adebe49464
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      rhdh.redhat.com/app: backstage-psql-my-rhdh
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "4661"
