apiVersion: v1
data:
  POSTGRES_HOST: [REDACTED]
  POSTGRES_PASSWORD: [REDACTED]
  POSTGRES_PORT: [REDACTED]
  POSTGRES_USER: [REDACTED]
  POSTGRESQL_ADMIN_PASSWORD: [REDACTED]
kind: Secret
metadata:
  creationTimestamp: "2025-10-23T11:12:30Z"
  labels:
    app.kubernetes.io/instance: my-developer-hub-op
    app.kubernetes.io/name: backstage
  name: backstage-psql-secret-my-developer-hub-op
  namespace: my-ns
  ownerReferences:
  - apiVersion: rhdh.redhat.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Backstage
    name: my-developer-hub-op
    uid: 61803723-6184-4c65-8836-9c7513554702
  resourceVersion: "40484"
  uid: d3ce8650-20ff-4ce1-8949-e6b25bea4388
type: Opaque
