apiVersion: v1
data:
  .dockercfg: [REDACTED]
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: deployer
  creationTimestamp: "2025-10-23T07:52:50Z"
  name: deployer-dockercfg-894vs
  namespace: my-ns
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: deployer
    uid: f5802411-d24e-41d1-8c32-2279e5a9fdc8
  resourceVersion: "36990"
  uid: 222b0670-e6d8-4c8c-9e82-7bf350675326
type: kubernetes.io/dockercfg
