---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-10-23T09:45:22Z"
  labels:
    kubernetes.io/metadata.name: my-ns-3
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: kubectl-create
    operation: Update
    time: "2025-10-23T09:45:22Z"
  name: my-ns-3
  resourceVersion: "1547"
  uid: 50230880-a4a7-46f0-888c-fe049754f179
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
